### ISSUE TITLE
Investigate release please module versioning with terraform

### ISSUE THREAD

**Issue by tonirvega** [prefapp/tfm#13]
# Motivation

Currently, we cannot publish a module with monorepo structure and release-please.

We tried to publish following this documentation, but it seems not working for a monorepo structure with the terraform-modules

# Docs

- https://github.com/googleapis/release-please#strategy-language-types-supported

**Comment by alambike** [comment]
Solved with this release-please config: https://github.com/prefapp/tfm/blob/4e324eea4d405f883d7779da566acdfed5c728a1/release-please-config.json
